import { doc, writeBatch } from 'firebase/firestore';
import { db } from '../firebase';
import { Employee } from '../types';

// Synthetic demo team for the AI Day booth.
// All names, emails, and content are fictitious. Designed so a visitor can:
//  - See a realistic mid-cycle roster (mixed statuses)
//  - Click into a Pending check-in and see goals + start writing
//  - Click into a Draft check-in to see a pre-populated rough draft they can
//    immediately click "Refine with AI" on (the killer demo)
//  - Click into a Submitted check-in to see what a finished one looks like
export const seedMockData = async (userEmail: string) => {
  const managerEmail = userEmail.toLowerCase();
  const now = new Date().toISOString();

  const mockEmployees: Partial<Employee>[] = [
    {
      id: 'aarya.patel@freshworks.com',
      employee_id: 'FW2001',
      employee_name: 'Aarya Patel',
      employee_email: 'aarya.patel@freshworks.com',
      first_name: 'Aarya',
      last_name: 'Patel',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Senior Software Engineer',
      job_family: 'Engineering',
      work_location: 'Bengaluru, India',
      grade: 'IC 4',
      goals: [
        {
          goal_name: 'Migrate notification service to event-driven pipeline',
          goal_category: 'Performance Objective',
          goal_description: 'Decouple the legacy synchronous notification system into asynchronous workers to reduce p95 latency from 2.4s to under 400ms.',
          status: 'Progressing',
          due_date: '2026-11-30T00:00:00.000Z',
          weight: 40,
        },
        {
          goal_name: 'Mentor two junior engineers through onboarding',
          goal_category: 'Development Goal',
          goal_description: 'Pair with two new IC2 engineers, lead biweekly architecture reviews, and shepherd them through their first production deployment.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 30,
        },
        {
          goal_name: 'Reduce on-call MTTR by 30%',
          goal_category: 'Performance Objective',
          goal_description: 'Improve runbook coverage, alert quality, and dashboards for the platform team.',
          status: 'Completed',
          due_date: '2026-05-31T00:00:00.000Z',
          weight: 30,
        },
      ],
      status: 'Pending',
      updated_at: now,
    },
    {
      id: 'chen.wei@freshworks.com',
      employee_id: 'FW2002',
      employee_name: 'Chen Wei',
      employee_email: 'chen.wei@freshworks.com',
      first_name: 'Chen',
      last_name: 'Wei',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Staff Product Designer',
      job_family: 'Design',
      work_location: 'Singapore',
      grade: 'IC 5',
      goals: [
        {
          goal_name: 'Lead design for the new onboarding experience',
          goal_category: 'Performance Objective',
          goal_description: 'Own end-to-end design for the redesigned customer onboarding flow targeting a 15% activation lift.',
          status: 'Progressing',
          due_date: '2026-09-30T00:00:00.000Z',
          weight: 50,
        },
        {
          goal_name: 'Establish a design system contribution model',
          goal_category: 'Audacious Goal',
          goal_description: 'Define and ship governance for cross-pod design system contributions.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 30,
        },
        {
          goal_name: 'Run quarterly design crits with engineering',
          goal_category: 'Development Goal',
          goal_description: 'Build a recurring forum to strengthen design-engineering collaboration.',
          status: 'Not Started',
          due_date: '2026-12-15T00:00:00.000Z',
          weight: 20,
        },
      ],
      status: 'Draft',
      mid_year_checkin: {
        key_contributions: 'really good on onboarding stuff. Drove the design well. Got positive feedback from PMs.',
        development_evolution: 'Could be more vocal in cross team reviews. Sometimes too quiet.',
        leadership_mastery: '',
        performance_trending_rating: '',
        promotion_readiness: null,
        additional_notes: '',
        great_reflections: [],
        submitted_at: null,
      },
      updated_at: now,
    },
    {
      id: 'dee.nguyen@freshworks.com',
      employee_id: 'FW2003',
      employee_name: 'Dee Nguyen',
      employee_email: 'dee.nguyen@freshworks.com',
      first_name: 'Dee',
      last_name: 'Nguyen',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Engineering Manager',
      job_family: 'Engineering',
      work_location: 'San Francisco, USA',
      grade: 'PM 4',
      goals: [
        {
          goal_name: 'Grow the platform pod from 6 to 10 engineers',
          goal_category: 'Performance Objective',
          goal_description: 'Hire 4 strong engineers across IC3-IC5 levels and ramp them through the first 90 days.',
          status: 'Progressing',
          due_date: '2026-10-31T00:00:00.000Z',
          weight: 40,
        },
        {
          goal_name: 'Ship the multi-region read replicas',
          goal_category: 'Performance Objective',
          goal_description: 'Cross-region replica architecture for the primary OLTP store with sub-100ms cross-region read latency.',
          status: 'Progressing',
          due_date: '2026-09-30T00:00:00.000Z',
          weight: 40,
        },
        {
          goal_name: 'Coach two ICs into tech-lead roles',
          goal_category: 'Development Goal',
          goal_description: 'Sustained 1:1 coaching plus visible project leadership opportunities.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 20,
        },
      ],
      status: 'Submitted',
      mid_year_checkin: {
        key_contributions: 'Dee has been the steady hand on the platform pod through a demanding half. Three of the four planned hires are closed (two IC4s and one IC5), all ramped onto on-call inside 60 days. The multi-region read-replica architecture shipped on schedule with sub-80ms p95 cross-region reads, beating the target. Most notable is the cultural shift in the pod — incident reviews are now collaborative rather than blame-oriented, and that came from Dee modeling it.',
        development_evolution: 'Dee tends to take on too much herself when a deadline gets tight, which slows down the team\'s growth on hard problems. The next stretch is to delegate the harder design conversations to the two ICs being coached into tech-lead roles, even when it would be faster to drive it personally. Comfort with intentional slowness in service of growth is the next edge.',
        leadership_mastery: 'Strong scores on Growth Mindset and Vision — Dee\'s pod has clear technical direction and reads as a place engineers want to be. Could lean further into Empowering — explicit delegation of architectural calls to the senior ICs would compound the team\'s strength.',
        performance_trending_rating: 'Exceeds Results',
        promotion_readiness: null,
        additional_notes: 'Dee is one cycle away from a strong PM5 conversation. Holding steady on this rating reflects the trajectory.',
        great_reflections: [],
        submitted_at: now,
      },
      updated_at: now,
    },
    {
      id: 'eli.park@freshworks.com',
      employee_id: 'FW2004',
      employee_name: 'Eli Park',
      employee_email: 'eli.park@freshworks.com',
      first_name: 'Eli',
      last_name: 'Park',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Software Engineer',
      job_family: 'Engineering',
      work_location: 'Seoul, South Korea',
      grade: 'IC 3',
      goals: [
        {
          goal_name: 'Own the billing reconciliation refactor',
          goal_category: 'Performance Objective',
          goal_description: 'Lead the rewrite of the nightly reconciliation job to handle 10x volume.',
          status: 'Progressing',
          due_date: '2026-08-31T00:00:00.000Z',
          weight: 50,
        },
        {
          goal_name: 'Reach independent code review readiness',
          goal_category: 'Development Goal',
          goal_description: 'Become a primary reviewer on the billing surface area.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 50,
        },
      ],
      status: 'Pending',
      updated_at: now,
    },
    {
      id: 'faiz.rahman@freshworks.com',
      employee_id: 'FW2005',
      employee_name: 'Faiz Rahman',
      employee_email: 'faiz.rahman@freshworks.com',
      first_name: 'Faiz',
      last_name: 'Rahman',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Senior Product Manager',
      job_family: 'Product',
      work_location: 'Dubai, UAE',
      grade: 'PM 4',
      goals: [
        {
          goal_name: 'Drive the AI-assisted ticket triage roadmap',
          goal_category: 'Performance Objective',
          goal_description: 'Define and ship the first three AI-assisted triage features measured against deflection lift.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 50,
        },
        {
          goal_name: 'Strengthen voice-of-customer signal',
          goal_category: 'Performance Objective',
          goal_description: 'Build a recurring rhythm for customer interviews tied to each major release.',
          status: 'Not Started',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 30,
        },
        {
          goal_name: 'Mentor an APM through end-to-end shipping',
          goal_category: 'Development Goal',
          goal_description: 'Pair on one product area through full lifecycle.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 20,
        },
      ],
      status: 'Draft',
      mid_year_checkin: {
        key_contributions: 'shipped the triage v1. customers like it. data shows good early signal.',
        development_evolution: 'needs to push back more on engineering scoping when timelines slip',
        leadership_mastery: '',
        performance_trending_rating: '',
        promotion_readiness: null,
        additional_notes: '',
        great_reflections: [],
        submitted_at: null,
      },
      updated_at: now,
    },
    {
      id: 'gabby.silva@freshworks.com',
      employee_id: 'FW2006',
      employee_name: 'Gabby Silva',
      employee_email: 'gabby.silva@freshworks.com',
      first_name: 'Gabby',
      last_name: 'Silva',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Senior Customer Success Manager',
      job_family: 'Customer Success',
      work_location: 'São Paulo, Brazil',
      grade: 'IC 4',
      goals: [
        {
          goal_name: 'Hit 95% net revenue retention on the LATAM book',
          goal_category: 'Performance Objective',
          goal_description: 'Lead renewal and expansion motions across the top 20 LATAM accounts.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 50,
        },
        {
          goal_name: 'Launch the quarterly executive review program',
          goal_category: 'Performance Objective',
          goal_description: 'Standardize QBR motion across the segment.',
          status: 'Completed',
          due_date: '2026-06-30T00:00:00.000Z',
          weight: 30,
        },
        {
          goal_name: 'Earn an internal speaking slot at the annual summit',
          goal_category: 'Development Goal',
          goal_description: 'Develop a point of view talk and pitch it for the company summit.',
          status: 'Progressing',
          due_date: '2026-11-30T00:00:00.000Z',
          weight: 20,
        },
      ],
      status: 'Pending',
      updated_at: now,
    },
    {
      id: 'hiro.tanaka@freshworks.com',
      employee_id: 'FW2007',
      employee_name: 'Hiro Tanaka',
      employee_email: 'hiro.tanaka@freshworks.com',
      first_name: 'Hiro',
      last_name: 'Tanaka',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Data Scientist',
      job_family: 'Data',
      work_location: 'Tokyo, Japan',
      grade: 'IC 4',
      goals: [
        {
          goal_name: 'Production-ize the churn propensity model',
          goal_category: 'Performance Objective',
          goal_description: 'Move the experimental churn model into a daily-scored production pipeline.',
          status: 'Progressing',
          due_date: '2026-10-31T00:00:00.000Z',
          weight: 50,
        },
        {
          goal_name: 'Set up the experimentation platform v0',
          goal_category: 'Audacious Goal',
          goal_description: 'Stand up the company\'s first internal A/B testing tool.',
          status: 'Not Started',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 30,
        },
        {
          goal_name: 'Run a monthly internal data office hours',
          goal_category: 'Development Goal',
          goal_description: 'Build internal data literacy through recurring office hours.',
          status: 'Progressing',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 20,
        },
      ],
      status: 'Pending',
      updated_at: now,
    },
    {
      id: 'iris.singh@freshworks.com',
      employee_id: 'FW2008',
      employee_name: 'Iris Singh',
      employee_email: 'iris.singh@freshworks.com',
      first_name: 'Iris',
      last_name: 'Singh',
      manager_email: managerEmail,
      manager_name: 'You',
      hrbp_name: 'Lab HRBP',
      hrbp_email: 'lab.hrbp@freshworks.com',
      job_title: 'Senior People Partner',
      job_family: 'People',
      work_location: 'London, UK',
      grade: 'IC 4',
      goals: [
        {
          goal_name: 'Run the EMEA mid-year cycle end-to-end',
          goal_category: 'Performance Objective',
          goal_description: 'Coordinate the mid-year performance cycle for the EMEA org of 480 people.',
          status: 'Progressing',
          due_date: '2026-07-15T00:00:00.000Z',
          weight: 40,
        },
        {
          goal_name: 'Build the EMEA manager enablement library',
          goal_category: 'Performance Objective',
          goal_description: 'Curate and produce the first cohort of manager enablement modules tailored to EMEA.',
          status: 'Progressing',
          due_date: '2026-11-30T00:00:00.000Z',
          weight: 40,
        },
        {
          goal_name: 'Earn the Coaching Foundations certification',
          goal_category: 'Development Goal',
          goal_description: 'Complete the external coaching foundations program.',
          status: 'Not Started',
          due_date: '2026-12-31T00:00:00.000Z',
          weight: 20,
        },
      ],
      status: 'Draft',
      mid_year_checkin: {
        key_contributions: 'super reliable on the cycle. people trust her. did a good job on enablement modules.',
        development_evolution: 'wants to do more strategic work. should take on more org design conversations.',
        leadership_mastery: '',
        performance_trending_rating: '',
        promotion_readiness: null,
        additional_notes: '',
        great_reflections: [],
        submitted_at: null,
      },
      updated_at: now,
    },
  ];

  const batch = writeBatch(db);
  mockEmployees.forEach((emp) => {
    batch.set(doc(db, 'employees', emp.id!), emp, { merge: true });
  });
  await batch.commit();
};
